### PR TITLE
Update dependencies, mainly namespace for AutoFixture 4

### PR DESCRIPTION
**Pull request by dbroudy**
@alexfoxgill The namespace changed for AutoFixture 4 since Mark Seemann is no longer maintaining it. Let me know if you'd like this broken out differently and I'd be happy to resubmit.

### CODE REVIEW

**Comment by alexfoxgill** [comment]
Thanks for the PR! This repo is no longer actively maintained (I'll add something in the readme to that effect) but I'll see if I can push out a NuGet version update when I have access to a windows machine

**Comment by dbroudy** [comment]
@alexfoxgill Thanks for the quick merge. I'd be interested in taking over maintenance, I have a pretty strong use case for it.

**Comment by alexfoxgill** [comment]
@dbroudy i just tried to transfer the repo to you but can't because your fork already exists - if you delete your fork i can transfer it. if you can give me your nuget username i will add you to the package for that too

**Comment by dbroudy** [comment]
I deleted my fork, and my nuget username is dbroudy. Thanks

**Comment by alexfoxgill** [comment]
repo and nuget transferred - thanks for taking it on

**Comment by dbroudy** [comment]
No problem. Thanks for creating it. I'll push out a release with these latest PRs shortly.

**Pull request merged**
